version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Comente a linha abaixo para garantir que o executável não seja sobreposto
    # volumes:
    #   - .:/app
    environment:
      - DATABASE_URL=sqlite.db
    command: ["/app/main"]
